name: IT Package Coverage

on:
  workflow_call:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:

  it-action-coverage-classes:

    name: IT Package Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for fixtures
        uses: actions/checkout@v3

      - name: Assert coverage of azbazeliner.pricer package is above or equal to 85% 
        uses: zlatko-ms/pycovcheck@main
        with: 
          coveragefile: ./test/fixtures/unit/nose2/coverage1.xml
          packages:  azbaseliner.pricing:0.85

      - name: Assert coverage of all packages is above or equal to 80% 
        uses: zlatko-ms/pycovcheck@main
        with: 
          coveragefile: ./test/fixtures/unit/nose2/coverage2.xml
          packages: :0.8